function BusData()
cellInfo = {...
    {...
    'AmberB1InBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'position_1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position_2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position_3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position_4', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position_5', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position_6', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'position_7', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    }...
    {...
    'AmberB1TorqueInBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'torque_1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque_2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque_3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque_4', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque_5', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque_6', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque_7', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    }...
    {...
    'AmberB1JointOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'velocity', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'torque', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    }...
    {...
    'AmberB1OutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'joint_1', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'joint_2', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'joint_3', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'joint_4', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'joint_5', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'joint_6', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'joint_7', 1, 'Bus: AmberB1JointOutBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    }...
    }...
    };
Simulink.Bus.cellToObject(cellInfo);
end